jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - 11
        - 10
      before_install:
        - npm i -g codecov
      script:
        - npm run test
      after_success:
        - codecov
      notifications:
        email:
          on_success: never
          on_failure: always
    # - stage: doc
    #   language: node_js
    #   node_js:
    #     - 11
    #   before_install:
    #     - npm i -g vuepress @vuepress/plugin-google-analytics@next
    #   script:
    #     - npm run docs:publish
    #   notifications:
    #     email:
    #       on_success: never
    #       on_failure: always
